version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring-net

  users-pg:
    image: postgres:15.2
    container_name: users-pg
    networks:
      - users-net
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: persons
    restart: always
    healthcheck:
      test: pg_isready -d users
      retries: 10
      interval: 10s
      start_period: 10s

  courses-mongo:
    image: mongo:6.0.4
    container_name: courses-mongo
    networks:
      - courses-net
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      retries: 10
      interval: 10s
      start_period: 10s

  users-api:
    build: /users
    container_name: users-api
    expose:
      - 8081
    networks:
      - users-net
      - spring-net
    depends_on:
      eureka-server:
        condition: service_started
      zipkin:
        condition: service_started
      users-pg:
        condition: service_healthy

  courses-api:
    build: /courses
    container_name: courses-api
    expose:
      - 8080
    networks:
      - courses-net
      - spring-net
    depends_on:
      eureka-server:
        condition: service_started
      zipkin:
        condition: service_started
      courses-mongo:
          condition: service_healthy

  eureka-server:
    build: /eureka-server
    container_name: eureka-server
    ports:
      - "9000:9000"
    networks:
      - spring-net
    depends_on:
      zipkin:
        condition: service_started

  gateway:  
    build: /gateway
    container_name: gateway
    networks:
      - spring-net
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started
      zipkin:
        condition: service_started

networks:
  users-net:
  courses-net:
  spring-net: