server:
  port: 8082

spring:
  application:
    name: courses
  data:
    mongodb:
      host: courses-mongo
      port: 27017
      username: root
      password: root
      database: courses
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9000/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"