server:
  port: 8081

spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://users-pg:5432/users
    username: postgres
    password: admin
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9000/eureka/
