server:
  port: 8083

spring:
  application:
    name: participations
  data:
    mongodb:
      host: participations-mongo
      port: 27017
      username: root
      password: root
      database: courses
      authentication-database: admin
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9000/eureka/

