server:
  port: 8080

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/users/**

        - id: courses
          uri: lb://courses
          predicates:
            - Path=/api/courses/**

        - id: participations
          uri: lb://participations
          predicates:
            - Path=/api/participations/**

        - id: badges
          uri: lb://badges
          predicates:
            - Path=/api/badges/**
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9000/eureka/