server:
  port: 8084

spring:
  application:
    name: badges
  data:
    mongodb:
      host: badges-mongo
      port: 27017
      username: root
      password: root
      database: badges
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:9000/eureka/
      defaultZone: http://eureka-server:9000/eureka/
  instance:
    metadata-map:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${management.server.port}"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
          env,health,
          info,metrics,
          loggers,mappings,prometheus

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"