server:
  port: 8087

spring:
  application:
    name: appli

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9000/eureka/


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  #  level:
  #    org:
  #      springframework:
  #        web: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"